sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: GEY6Y+szpOc50YN/R5UJFUv9P6OXaNkaj2fUEVq96Pp40YCImHt8jU9R/I6NujukAPWTtal+65Xg+alGEieY4CUq8hUODbsHwoEpWGe0vtNCWcwXlCHET3Z7mFH8zmGGi6vwb+y+3FIcxicL7hvVCr2F1ZVv8EVjBUfmdGp4UBTfWTUHdgc8b0qp5maEDz2LXT+efaWph4C2aH6eLEe+R7weYmToqR66+4SnnIgDCEvIfXU2b2XsXfseVE+LF/3mIz+miC00zedrkwahRf2Es6lzJQDAQKvmiua7hDBVsOi56o81z7PE/ny4FClhDUUtZdt4eNn5i+NUUyl9xlf12mPXcEXuallpE2RJUsgiWoX+OgTbjSm1oWhaOpcrm+77TAzI+OXD+kFHpM3vzFLMO6IGDtwfyMRcGgWZ+I2cZi0HHalQ43JQm45c4BeSCpcP6UsoC1wXHWUh5YKNBn2Tn1RPL5IPt6bdr3xcdjOKVN55igMbrScNxd+Ve+jnIpeFt7Jh21fhcYznF3oPY5iNyQOOi3mrq0R5BTGqENP0VaZSMHwpVSNMv+NPQh/Z00FtnvBI82noJfswAe6VfZZHyGjaVhtZhr8mFtE37YUQpozQvK5LSimRIHYjX2yBaC/fM3WxFBABJxrG2o+c/nhvB/KOD3SyUDzBAIJpkRgq62k=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Innocence-of-Father-Brown_204
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy